//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNumber
    {
        public int id { get; set; }
        public System.DateTime today { get; set; }
        public int SeqNumber { get; set; }
        public int OrderType { get; set; }
    }
}
