//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAdjustmentHistory
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int AdjustedQuantity { get; set; }
        public string Reason { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
