//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mics.Web.Api
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Vendor
    {
        [Key]
        public int VendorID { get; set; }
        public int AddressID { get; set; }
        public string AccountNumber { get; set; }
        public string Name { get; set; }
        public string ContactName { get; set; }
        public byte CreditRating { get; set; }
        public bool PreferredVendorStatus { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public bool ActiveFlag { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string AltPhone { get; set; }
        public string Terms { get; set; }
    }
}
