//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mics.Web.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceDetail
    {
        public int InvoiceID { get; set; }
        public int InvoiceDetailID { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public long Quantity { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
