//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mics.Web.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public int PurchaseOrderID { get; set; }
        public int PurchaseOrderDetailID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public short OrderQty { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<double> NumberOfCases { get; set; }
        public Nullable<int> UnitPerCase { get; set; }
        public long ReceivedQty { get; set; }
        public long RejectedQty { get; set; }
        public Nullable<long> StockedQty { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
